= Polkadot
:Author: Polkadot developers
:Revision: 0.2.0
:toc:
:sectnums:

== Intro

Implementation of a https://polkadot.network node in Rust.


== To play

If you'd like to play with Polkadot, you'll need to install a client like this
one. First, get Rust (1.26.1 or later) and the support software if you don't already have it:

[source, shell]
----
curl https://sh.rustup.rs -sSf | sh
sudo apt install make clang pkg-config libssl-dev
----

Then, install Polkadot PoC-2:

[source, shell]
cargo install --git https://github.com/paritytech/polkadot.git --branch v0.2 polkadot

You'll now have a `polkadot` binary installed to your `PATH`. You can drop the
`--branch v0.2` or run `cargo install --git https://github.com/paritytech/polkadot.git polkadot`
to get the very latest version of Polkadot, but these instructions might not work in that case.

If you want a specific version of polkadot, say `0.2.2`, you may run `cargo install --git https://github.com/paritytech/polkadot.git --tag v0.2.2 polkadot`.

include::doc/networks/networks.adoc[]

== Hacking on Polkadot

If you'd actually like hack on Polkadot, you can just grab the source code and
build it. Ensure you have Rust and the support software installed:

[source, shell]
----
curl https://sh.rustup.rs -sSf | sh
rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly
rustup update stable
cargo install --git https://github.com/alexcrichton/wasm-gc
sudo apt install cmake pkg-config libssl-dev git
----

Then, grab the Polkadot source code:

[source, shell]
----
git clone https://github.com/paritytech/polkadot.git
cd polkadot
----

Then build the code:

[source, shell]
----
./scripts/build.sh  # Builds the WebAssembly binaries
cargo build # Builds all native code
----

You can run the tests if you like:

[source, shell]
cargo test --all

You can start a development chain with:

[source, shell]
cargo run -- --dev


include::doc/packages/packages.adoc[]

include::doc/docker.adoc[]

include::doc/shell-completion.adoc[]

:leveloffset: +1

include::CONTRIBUTING.adoc[]

:leveloffset: -1

:leveloffset: +1

include::CODE_OF_CONDUCT.adoc[]

:leveloffset: -1

== License

----
include::LICENSE[]
----
