// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_election_provider_support_onchain
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-03-27, STEPS: `1`, REPEAT: 1, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/substrate
// benchmark
// --chain=dev
// --steps=1
// --repeat=1
// --pallet=pallet_election_provider_support_onchain
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=frame/election-provider-support/onchain/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_election_provider_support_onchain.
pub trait WeightInfo {
	fn phragmen(v: u32, t: u32, d: u32, ) -> Weight;
	fn phragmms(v: u32, t: u32, d: u32, ) -> Weight;
}

/// Weights for pallet_election_provider_support_onchain using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: BagsList CounterForListNodes (r:1 w:0)
	// Storage: Staking SlashingSpans (r:1 w:0)
	// Storage: BagsList ListBags (r:200 w:0)
	// Storage: BagsList ListNodes (r:2000 w:0)
	// Storage: Staking Nominators (r:2000 w:0)
	// Storage: Staking Validators (r:1001 w:0)
	// Storage: Staking Bonded (r:2000 w:0)
	// Storage: Staking Ledger (r:2000 w:0)
	// Storage: Staking CounterForValidators (r:1 w:0)
	// Storage: Staking ValidatorCount (r:1 w:0)
	fn phragmen(v: u32, t: u32, d: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 4_551_000
			.saturating_add((28_316_000 as Weight).saturating_mul(v as Weight))
			// Standard Error: 9_102_000
			.saturating_add((33_176_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 413_754_000
			.saturating_add((241_364_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(205 as Weight))
			.saturating_add(T::DbWeight::get().reads((4 as Weight).saturating_mul(v as Weight)))
			.saturating_add(T::DbWeight::get().reads((5 as Weight).saturating_mul(t as Weight)))
	}
	// Storage: BagsList CounterForListNodes (r:1 w:0)
	// Storage: Staking SlashingSpans (r:1 w:0)
	// Storage: BagsList ListBags (r:200 w:0)
	// Storage: BagsList ListNodes (r:2000 w:0)
	// Storage: Staking Nominators (r:2000 w:0)
	// Storage: Staking Validators (r:1001 w:0)
	// Storage: Staking Bonded (r:2000 w:0)
	// Storage: Staking Ledger (r:2000 w:0)
	// Storage: Staking CounterForValidators (r:1 w:0)
	// Storage: Staking ValidatorCount (r:1 w:0)
	fn phragmms(v: u32, t: u32, d: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 1_717_000
			.saturating_add((31_202_000 as Weight).saturating_mul(v as Weight))
			// Standard Error: 3_434_000
			.saturating_add((43_895_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 156_131_000
			.saturating_add((781_424_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(205 as Weight))
			.saturating_add(T::DbWeight::get().reads((4 as Weight).saturating_mul(v as Weight)))
			.saturating_add(T::DbWeight::get().reads((5 as Weight).saturating_mul(t as Weight)))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: BagsList CounterForListNodes (r:1 w:0)
	// Storage: Staking SlashingSpans (r:1 w:0)
	// Storage: BagsList ListBags (r:200 w:0)
	// Storage: BagsList ListNodes (r:2000 w:0)
	// Storage: Staking Nominators (r:2000 w:0)
	// Storage: Staking Validators (r:1001 w:0)
	// Storage: Staking Bonded (r:2000 w:0)
	// Storage: Staking Ledger (r:2000 w:0)
	// Storage: Staking CounterForValidators (r:1 w:0)
	// Storage: Staking ValidatorCount (r:1 w:0)
	fn phragmen(v: u32, t: u32, d: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 4_551_000
			.saturating_add((28_316_000 as Weight).saturating_mul(v as Weight))
			// Standard Error: 9_102_000
			.saturating_add((33_176_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 413_754_000
			.saturating_add((241_364_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(RocksDbWeight::get().reads(205 as Weight))
			.saturating_add(RocksDbWeight::get().reads((4 as Weight).saturating_mul(v as Weight)))
			.saturating_add(RocksDbWeight::get().reads((5 as Weight).saturating_mul(t as Weight)))
	}
	// Storage: BagsList CounterForListNodes (r:1 w:0)
	// Storage: Staking SlashingSpans (r:1 w:0)
	// Storage: BagsList ListBags (r:200 w:0)
	// Storage: BagsList ListNodes (r:2000 w:0)
	// Storage: Staking Nominators (r:2000 w:0)
	// Storage: Staking Validators (r:1001 w:0)
	// Storage: Staking Bonded (r:2000 w:0)
	// Storage: Staking Ledger (r:2000 w:0)
	// Storage: Staking CounterForValidators (r:1 w:0)
	// Storage: Staking ValidatorCount (r:1 w:0)
	fn phragmms(v: u32, t: u32, d: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 1_717_000
			.saturating_add((31_202_000 as Weight).saturating_mul(v as Weight))
			// Standard Error: 3_434_000
			.saturating_add((43_895_000 as Weight).saturating_mul(t as Weight))
			// Standard Error: 156_131_000
			.saturating_add((781_424_000 as Weight).saturating_mul(d as Weight))
			.saturating_add(RocksDbWeight::get().reads(205 as Weight))
			.saturating_add(RocksDbWeight::get().reads((4 as Weight).saturating_mul(v as Weight)))
			.saturating_add(RocksDbWeight::get().reads((5 as Weight).saturating_mul(t as Weight)))
	}
}
