{
 "title": "Substrate Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "network", "query": "label_values(network)" },
   { "name": "hostname", "query": "label_values(hostname)" }
  ]
 },
 "panels": [
  {
   "title": "Relative Block Production Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(polkadot_block_height_number{status=\"finalized\",hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}[10m])/rate(polkadot_block_height_number{status=\"finalized\",hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}[1m])",
     "legendFormat": "rate[10m] / rate[1m]"
    }
   ]
  },
  {
   "title": "Peers count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_sub_libp2p_peers_count{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Diff -> ( Best Block - Finalized )",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(polkadot_block_height_number{status=\"best\",hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"})-scalar(polkadot_block_height_number{status=\"finalized\",hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"})",
     "legendFormat": "[[hostname]]"
    }
   ]
  },
  {
   "title": "Block rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(polkadot_block_height_number{status=\"finalized\",hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}[10m])*60",
     "legendFormat": "{{hostname}}  Blocks / minute"
    }
   ]
  },
  {
   "title": "Blocks Av per min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(polkadot_block_height_number{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\",status=~\"finalized|sync_target\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Block Finalized",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_block_height_number{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\",status=~\"finalized|sync_target\"}",
     "legendFormat": "{{hostname}} {{status}}"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_block_height_number{status=\"best\",hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "TXs Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_ready_transactions_number{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}}",
     "target": "txcount",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Sync Proof",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_sync_extra_finality_proofs_active{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} active"
    },
    {
     "expr": "polkadot_sync_extra_finality_proofs_failed{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} failed"
    },
    {
     "expr": "polkadot_sync_extra_finality_proofs_importing{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} importing"
    },
    {
     "expr": "polkadot_sync_extra_finality_proofs_pending{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} pending"
    }
   ]
  },
  {
   "title": "Sync justifications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_sync_extra_justifications_active{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} active"
    },
    {
     "expr": "polkadot_sync_extra_justifications_failed{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} failed"
    },
    {
     "expr": "polkadot_sync_extra_justifications_importing{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} importing"
    },
    {
     "expr": "polkadot_sync_extra_justifications_pending{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} pending"
    }
   ]
  },
  {
   "title": "sub_libp2p",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_sub_libp2p_connections{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} connections"
    },
    {
     "expr": "polkadot_sub_libp2p_is_major_syncing{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} syncing"
    },
    {
     "expr": "polkadot_sub_libp2p_kbuckets_num_nodes{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} num_nodes"
    }
   ]
  },
  {
   "title": "libp2p_notifications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_sub_libp2p_notifications_total{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\",protocol=\"FRNK\",direction=\"in\"}",
     "legendFormat": "{{hostname}} FRNK in"
    },
    {
     "expr": "polkadot_sub_libp2p_notifications_total{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\",protocol=\"FRNK\",direction=\"out\"}",
     "legendFormat": "{{hostname}} FRNK out"
    }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_cpu_usage_percentage{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "polkadot_memory_usage_bytes{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} Mem bytes"
    }
   ]
  },
  {
   "title": "libp2p_network_per_sec_bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_sub_libp2p_network_per_sec_bytes",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "libp2p_notifications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_sub_libp2p_notifications_total{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\",protocol=\"dot1\",direction=\"in\"}",
     "legendFormat": "{{hostname}} dot1 in"
    },
    {
     "expr": "polkadot_sub_libp2p_notifications_total{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\",protocol=\"dot2\",direction=\"in\"}",
     "legendFormat": "{{hostname}} dot2 in"
    },
    {
     "expr": "polkadot_sub_libp2p_notifications_total{hostname=\"[[hostname]]\",job=\"polkadot_[[hostname]]\",network=\"[[network]]\",protocol=\"dot2\",direction=\"out\"}",
     "legendFormat": "{{hostname}} dot2 out"
    }
   ]
  }
 ]
}