(function() {var implementors = {
"frame_support_test_compile_pass":[["impl <a class=\"trait\" href=\"frame_system/pallet/trait.Config.html\" title=\"trait frame_system::pallet::Config\">Config</a> for <a class=\"struct\" href=\"frame_support_test_compile_pass/struct.Runtime.html\" title=\"struct frame_support_test_compile_pass::Runtime\">Runtime</a>"]],
"kitchensink_runtime":[["impl <a class=\"trait\" href=\"frame_system/pallet/trait.Config.html\" title=\"trait frame_system::pallet::Config\">Config</a> for <a class=\"struct\" href=\"kitchensink_runtime/struct.Runtime.html\" title=\"struct kitchensink_runtime::Runtime\">Runtime</a>"]],
"node_template_runtime":[["impl <a class=\"trait\" href=\"frame_system/pallet/trait.Config.html\" title=\"trait frame_system::pallet::Config\">Config</a> for <a class=\"struct\" href=\"node_template_runtime/struct.Runtime.html\" title=\"struct node_template_runtime::Runtime\">Runtime</a>"]],
"pallet_bags_list":[["impl <a class=\"trait\" href=\"frame_system/pallet/trait.Config.html\" title=\"trait frame_system::pallet::Config\">Config</a> for <a class=\"struct\" href=\"pallet_bags_list/mock/struct.Runtime.html\" title=\"struct pallet_bags_list::mock::Runtime\">Runtime</a>"]],
"pallet_default_config_example":[["impl <a class=\"trait\" href=\"frame_system/pallet/trait.Config.html\" title=\"trait frame_system::pallet::Config\">Config</a> for <a class=\"struct\" href=\"pallet_default_config_example/tests/struct.Runtime.html\" title=\"struct pallet_default_config_example::tests::Runtime\">Runtime</a>"]],
"pallet_nomination_pools":[["impl <a class=\"trait\" href=\"frame_system/pallet/trait.Config.html\" title=\"trait frame_system::pallet::Config\">Config</a> for <a class=\"struct\" href=\"pallet_nomination_pools/mock/struct.Runtime.html\" title=\"struct pallet_nomination_pools::mock::Runtime\">Runtime</a>"]],
"pallet_paged_list":[["impl <a class=\"trait\" href=\"frame_system/pallet/trait.Config.html\" title=\"trait frame_system::pallet::Config\">Config</a> for <a class=\"struct\" href=\"pallet_paged_list/mock/struct.Test.html\" title=\"struct pallet_paged_list::mock::Test\">Test</a>"]],
"substrate_test_runtime":[["impl <a class=\"trait\" href=\"frame_system/pallet/trait.Config.html\" title=\"trait frame_system::pallet::Config\">Config</a> for <a class=\"struct\" href=\"substrate_test_runtime/struct.Runtime.html\" title=\"struct substrate_test_runtime::Runtime\">Runtime</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()