{
 "title": "Substrate Networking",
 "description": "Information related to the networking layer of Substrate",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metric_namespace", "label": "Chain Metrics", "query": "substrate, polkadot" },
   {
    "name": "nodename",
    "label": "Instance name filter",
    "query": "${metric_namespace}_process_start_time_seconds"
   },
   {
    "name": "notif_protocol",
    "query": "${metric_namespace}_sub_libp2p_notifications_streams_opened_total{instance=~\"${nodename}\"}"
   },
   {
    "name": "request_protocol_in",
    "query": "${metric_namespace}_sub_libp2p_requests_in_success_total_count{instance=~\"${nodename}\"}"
   },
   { "name": "data_source", "label": "Source of data", "query": "prometheus" },
   {
    "name": "request_protocol_out",
    "query": "${metric_namespace}_sub_libp2p_requests_out_success_total_count{instance=~\"${nodename}\"}"
   }
  ]
 },
 "panels": [
  { "title": "Transport", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average transport-level (TCP, QUIC, ...) connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"in\", instance=~\"${nodename}\"}) by (instance) -\n  sum(${metric_namespace}_sub_libp2p_connections_closed_total{direction=\"in\", instance=~\"${nodename}\"}) by (instance)\n)\n\n# Because `closed_total` can be null, this serves as fallback\nor on(instance) sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"in\", instance=~\"${nodename}\"}) by (instance)",
     "legendFormat": "established (in)"
    },
    {
     "expr": "(\n  sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"out\", instance=~\"${nodename}\"}) by (instance) -\n  sum(${metric_namespace}_sub_libp2p_connections_closed_total{direction=\"out\", instance=~\"${nodename}\"}) by (instance)\n)\n\n# Because `closed_total` can be null, this serves as fallback\nor on(instance) sum(${metric_namespace}_sub_libp2p_connections_opened_total{direction=\"out\", instance=~\"${nodename}\"}) by (instance)",
     "legendFormat": "established (out)"
    },
    {
     "expr": "sum by (instance) (${metric_namespace}_sub_libp2p_pending_connections{instance=~\"${nodename}\"})",
     "legendFormat": "pending (out)"
    },
    {
     "expr": "sum(rate(${metric_namespace}_sub_libp2p_connections_closed_total{instance=~\"${nodename}\"}[$__interval]))",
     "legendFormat": "closed-per-sec"
    }
   ]
  },
  {
   "title": "Percentage of peers for which we have more than one connection open",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - \n\navg(\n  ${metric_namespace}_sub_libp2p_distinct_peers_connections_opened_total{instance=~\"${nodename}\"} - ${metric_namespace}_sub_libp2p_distinct_peers_connections_closed_total{instance=~\"${nodename}\"}\n) by (instance)\n\n/\n\navg(\r\n  sum(${metric_namespace}_sub_libp2p_connections_opened_total{instance=~\"${nodename}\"}) by (instance) - sum(${metric_namespace}_sub_libp2p_connections_closed_total{instance=~\"${nodename}\"}) by (instance)\r\n) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of incoming connection errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(${metric_namespace}_sub_libp2p_incoming_connections_handshake_errors_total{instance=~\"${nodename}\"}[$__rate_interval])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "increase(${metric_namespace}_sub_libp2p_listeners_errors_total{instance=~\"${nodename}\"}[$__rate_interval])",
     "legendFormat": "pre-handshake"
    }
   ]
  },
  {
   "title": "Network bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_network_bytes_total{instance=~\"${nodename}\"}[$__rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Dialing attempt errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(${metric_namespace}_sub_libp2p_pending_connections_errors_total{instance=~\"${nodename}\"}[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Disconnects/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "cps", "label": "Disconnects" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_connections_closed_total{instance=~\"${nodename}\"}[$__rate_interval])",
     "legendFormat": "{{reason}} ({{direction}})"
    }
   ]
  },
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Number of peer slots filled",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "${metric_namespace}_sub_libp2p_peerset_num_requested{instance=~\"${nodename}\"}",
     "legendFormat": "peers-requested"
    },
    {
     "expr": "${metric_namespace}_sub_libp2p_peers_count{instance=~\"${nodename}.*\"}",
     "legendFormat": "peers-count"
    }
   ]
  },
  {
   "title": "Outbound requests (${request_protocol_out})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "repeat": "request_protocol_out"
  },
  {
   "title": "Requests emitted per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 46 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_requests_out_success_total_count{instance=~\"${nodename}\", protocol=\"${request_protocol_out}\"}[$__rate_interval]) + on(instance) sum(rate(${metric_namespace}_sub_libp2p_requests_out_failure_total{instance=~\"${nodename}\", protocol=\"${request_protocol_out}\"}[$__rate_interval])) by (instance)\n\nor\n\nrate(${metric_namespace}_sub_libp2p_requests_out_success_total_count{instance=~\"${nodename}\", protocol=\"${request_protocol_out}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outbound requests failures (other than \"obsolete\")",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 50 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(${metric_namespace}_sub_libp2p_requests_out_failure_total{instance=~\"${nodename}\", protocol=\"${request_protocol_out}\", reason != \"obsolete\"}[$__rate_interval])) by (instance, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Median request answer time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 54 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(${metric_namespace}_sub_libp2p_requests_out_success_total_bucket{instance=~\"${nodename}\", protocol=\"${request_protocol_out}\"}[$__rate_interval])) by (instance, le)) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99th percentile request answer time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 58 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(${metric_namespace}_sub_libp2p_requests_out_success_total_bucket{instance=~\"${nodename}\", protocol=\"${request_protocol_out}\"}[$__rate_interval])) by (instance, le)) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inbound requests (${request_protocol_in})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "repeat": "request_protocol_in"
  },
  {
   "title": "Requests served per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 63 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_requests_in_success_total_count{instance=~\"${nodename}\", protocol=\"${request_protocol_in}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inbound requests failures",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 67 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(${metric_namespace}_sub_libp2p_requests_in_failure_total{instance=~\"${nodename}\", protocol=\"${request_protocol_in}\"}[$__rate_interval])) by (instance, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Median request serving time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 71 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(${metric_namespace}_sub_libp2p_requests_in_success_total_bucket{instance=~\"${nodename}\", protocol=\"${request_protocol_in}\"}[$__rate_interval])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99th percentile request serving time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 75 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(${metric_namespace}_sub_libp2p_requests_in_success_total_bucket{instance=~\"${nodename}\", protocol=\"${request_protocol_in}\"}[$__rate_interval])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Notifications (${notif_protocol})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "repeat": "notif_protocol"
  },
  {
   "title": "Number of open substreams",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${metric_namespace}_sub_libp2p_notifications_streams_opened_total{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"} - ${metric_namespace}_sub_libp2p_notifications_streams_closed_total{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Substreams closed/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_sub_libp2p_notifications_streams_closed_total{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of network notifications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 92 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short", "label": "Notifs/sec" }
   ],
   "targets": [
    {
     "expr": "avg by (direction) (rate(${metric_namespace}_sub_libp2p_notifications_sizes_count{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[$__rate_interval]))",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Average bandwidth used by notifications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 98 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "Bps", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "expr": "avg(rate(${metric_namespace}_sub_libp2p_notifications_sizes_sum{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[$__rate_interval])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Total sizes of notifications waiting to be delivered to the rest of Substrate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 104 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "${metric_namespace}_sub_libp2p_out_events_notifications_sizes{instance=~\"${nodename}\", protocol=\"${notif_protocol}\", action=\"sent\"} - ignoring(action) ${metric_namespace}_sub_libp2p_out_events_notifications_sizes{instance=~\"${nodename}\", protocol=\"${notif_protocol}\", action=\"received\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average size of sent and received notifications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 110 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "bytes", "label": "Max. notification size" }
   ],
   "targets": [
    {
     "expr": "sum(rate(${metric_namespace}_sub_libp2p_notifications_sizes_sum{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[$__rate_interval])) by (direction, protocol) / sum(rate(${metric_namespace}_sub_libp2p_notifications_sizes_count{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[$__rate_interval])) by (direction, protocol)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "99th percentile of size of sent and received notifications",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 116 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "bytes", "label": "Max. notification size" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(${metric_namespace}_sub_libp2p_notifications_sizes_bucket{instance=~\"${nodename}\", protocol=\"${notif_protocol}\"}[$__rate_interval])) by (direction, le))",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "GrandPa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "GrandPa messages received from the network, and action",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 123 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(${metric_namespace}_finality_grandpa_communication_gossip_validator_messages{instance=~\"${nodename}\"}[$__interval])",
     "legendFormat": "{{message}} => {{action}}"
    }
   ]
  },
  { "title": "Kademlia & authority-discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Kademlia and Authority Discovery metrics moved to \"kademlia-and-authority-discovery\" dashboard.",
   "type": "dashlist",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 }
  }
 ]
}