= Structure
:Author: Substrate developers
:Revision: 0.3.0
:toc:
:sectnums:


== Overview

Substrate is split into multiple levels with increasing opinion and decreasing flexibility:

* primitives
* client
* PAINT (formerly `paint`)

Putting all these components together we have:

* Integration Tests
* Node
* Node template
* Subkey

=== Runtime

* _found in_: `/primitives`
* _crates prefix_: `sp-`
* _constrains_:
** must be `[no_std]`
** crates may not (dev-)depend on crates in other subfolders of this repo

In the lowest level, substrate defines primitives, interfaces and traits to implement any on-chain substrate transition system and its interactions with the outside world. This is the lowest level of abstraction and opinion everything else builds upon.

=== Client

* _found in_: `/client`
* _crates prefix_: `substrate-`
* _constrains_:
** crates may not (dev-)depend on any `paint-`-crates

In the client you can find a set of crates to construct the outer substrate-node, implementing outer runtime interfaces, thus it depends on `runtime`. It provides the outer building blocks like transaction queue, networking layer, database backend, full* and light-client support.

=== PAINT (formerly `paint`)

* _found in_: `/paint`
* _crates prefix_: `paint-`
* _constrains_:
** all crates that go on chain, must be `[no_std]`
** must not (dev-)depend on anything in `/client`

PAINT, the Parity Application Interface for Network-wide Transitions, is a set of modules implementing specific transition functions and features one (might) want to have in their runtime.

=== integration tests

* _found in_: `/test`
* _crates prefix_: `substrate-test`
* _constrains_:
** only helpers may be published
** purely testing crates must be `publish = false`

All tests that have to pull (dev)-dependencies out of their substree and would thus break the dependency rules, are considered intergration tests and should be stored in here. Only helper-crates in here shall be published, everything else is expected to be non-publish.

=== Binaries and template

* _found in_: `/bin`

We also provide some binaries pulling from the components creating full applications.

==== Node

* _found in_: `/bin/node`

The default (testing) application pulling together our recommended setup of substrate-client with a wasm-contracts-supporting paint-runtime.  The node pulls it all together, constructs the (upgradable) runtime and wires up the client around it. You can find an example client, which includes a full wasm-contracts chain in  `node`. This is also what is being build and run if you do `cargo run`.


==== Node Template

* _found in_: `/bin/node-template`

We also provide a template to get you started building your own node.

==== Subkey

* _found in_: `/bin/subkey`

Subkey is a client library to generate keys and sign transactions to send to a substrate node.

== Internal Dependency Tree

[ditaa]
....
+---------------+       +----------------+
|               |       |                |
|    runtime    +<------+   paint        |
|               |       |                |
+------+-----+--+       +-------------+--+
       ^     ^                        ^
       |     +----------------+       |
       |                      |       |
+------+--------+             |       |
|               |             |       |
|   client      |          +--+-------+--------+
|               +<---------+                   |
+---------------+          |                   |
                           |   test  /bin/*    |
                           |                   |
                           |                   |
                           +-------------------+

....

